# Generated by Django 5.1.6 on 2025-04-28 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_remove_post_allow_comments_remove_post_pdated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='allow_comments',
            field=models.BooleanField(default=True),
        ),
    ]
